import type { Metadata } from "next";
import "./globals.css";
import { Tiro_Bangla } from "next/font/google";
import Providers from "@/lib/Provider";

const tiro_Bangla = Tiro_Bangla({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "sarabelanews24",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico', 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">  
      
      <Providers>
        <body className={`bg-white dark:bg-gray-800  dark:text-white ${tiro_Bangla.className}`}>{children}</body>
      </Providers>
    </html>
  );
}
